### ISSUE TITLE
F4 key binding isn't effective in 2023-06

### ISSUE THREAD

**Issue by basinilya** [eclipse-platform/.github#138] opened 2023-07-16 17:17 UTC
I'm comparing fresh copies of Eclipse for Java 2023-03 and 2023-06 (with fresh workspaces). Both have F4 key bound to Open Type Hierarchy (In Windows). In 2023-06 when pressing F4 nothing happens and in the context menu in java editor "Open Type Hierarchy" shows no effective binding.

The keys dialog shows no binding conflicts. Binding F4 to some other action like "About" is not effective. Rebinding "Open Type Hierarchy" to Shift-F4 is possible and this key combination works.

Is see no related messages in Error Log.

Eclipse IDE for Java Developers (includes Incubating components)
Version: 2023-06 (4.28.0)
Build id: 20230608-1333
[configuration.txt](https://github.com/eclipse-platform/.github/files/12064659/configuration.txt)

**Comment by iloveeclipse** [comment] 2023-07-16 20:27
Duplicate of https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/644

**Closed by iloveeclipse** 2023-07-16 20:27 UTC
