### ISSUE TITLE
Could not resolve module: org.apache.aries.spifly.dynamic.bundle

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/.github#145] opened 2023-08-15 07:08 UTC
logged in I-builds:

for example https://download.eclipse.org/eclipse/downloads/drops4/I20230814-1800/testresults/ep429I-unit-win32-java17_win32.win32.x86_64_17/directorLogs/director-org.eclipse.jdt.core.tests.compiler.log
```
file:C:\Users\genie.releng\workspace\AutomatedTests\ep429I-unit-win32-java17/workarea/I20230814-1800/eclipse-testing/testRepo

!ENTRY org.apache.aries.spifly.dynamic.bundle 4 0 2023-08-15 02:50:43.939
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.apache.aries.spifly.dynamic.bundle [2]
  Unresolved requirement: Import-Package: org.objectweb.asm; version="[9.4.0,10.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1852)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1845)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1788)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1750)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:445)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:464)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:139)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:651)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:588)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1459)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1432)
Aug 15, 2023 2:50:45 AM org.apache.aries.spifly.BaseActivator log
```

**Comment by iloveeclipse** [comment] 2023-08-15 07:21
Duplicate of https://github.com/eclipse-equinox/equinox/issues/302

**Closed by iloveeclipse** 2023-08-15 07:21 UTC
