### ISSUE TITLE
JVM crashes on MacOS Ventura w/ SWT browser

### ISSUE THREAD

**Issue by kentxu** [eclipse-platform/.github#74] opened 2022-10-27 22:19 UTC
To reproduce:
1. start eclipse and open internal browser view
2. type http://www.google.com

The entire JVM crashes. 9/10 times it crashes right away. Sometimes, it may last a bit longer.

This only started happening after upgrading to MacOS Ventura 13.0 released a couple of days ago.

It is reproducible on Eclipse 202206 and 202209 using the clean Eclipse IDE download without any changes. 

**Additional information:** I also have a RCP product and am getting similar reports from the clients who upgraded to Ventura. However, I am unable to reproduce the issue when the same RCP application is launched in the eclipse environment w/ the same target platform and Java. It only happens in the generated product. 

The problem also only happens if the browser URL is set and the html page must have some Javascript code.  I noticed that a single line of alert or jquery button click does not crashes the JVM, but it does crash when I put a dummy loop 1...100000 in the click callback.

A crash report is attached.

[crashreport.txt](https://github.com/eclipse-platform/.github/files/9883459/crashreport.txt)

A simple browser test. This never crashed during the test when launching from Eclipse.  Even though Eclipse's own "internal web browser" crashes 9/10 times within a second of loading the google home page (or any other html with scripting).  

Removing the following from the eclipse.ini file seems to help a bit... not sure yet
-XX:+UseG1GC
-XX:+UseStringDeduplication

**Comment by akurtakov** [comment] 2022-10-28 06:00
This seems duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/452

**Closed by akurtakov** 2022-10-28 06:00 UTC
