### ISSUE TITLE
When I lauche Eclipse I get error :"Failed to retrieve Windows Defender status" (I don't hava Defender, but another antivirus)

### ISSUE THREAD

**Issue by piradix** [eclipse-platform/.github#192] opened 2024-03-15 19:54 UTC
Let's make sure issue is not already fixed in latest builds first.

- [x] I verified I can reproduce this issue against [latest Integration Build of Eclipse SDK](https://download.eclipse.org/eclipse/downloads/)

## Steps to reproduce

From a fresh installation or a clean workspace, when I lauch Eclipse, I get directly a dialog box with error : "Failed to retrieve Windows Defender status."

* *Lauche Eclipse*

I tried

* *update a existing Eclipse*
* *a new Eclipse installation, from a zip archive*

I expected: *no error*

But got: *A dialog box with the error "Failed to retrieve Windows Defender status."*

## Here is some relevant log output

From `<workspace>/.metadata/.log`
```
Failed to retrieve Windows Defender status.
java.io.IOException: Process terminated with unexpected result:
Passive Mode
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.isWindowsDefenderActive(WindowsDefenderConfigurator.java:321)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.runExclusionCheck(WindowsDefenderConfigurator.java:154)
	at org.eclipse.ui.internal.WindowsDefenderConfigurator.lambda$0(WindowsDefenderConfigurator.java:101)
	at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

eclipse.buildId=4.31.0.20240307-1200
java.version=21.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=fr_FR
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

```

## Tested under this environment:
* Windows 11 pro
* Eclipse IDE/Platform version Version: 2024-03 (4.31.0) , Build id: 20240307-1437
* I dont'use Windows Defender, but BitDefender
* The probleme comme after update , ou a new install

## Community

- [x] I understand reporting an issue to this OSS project does not mandate anyone to fix it. Other contributors may consider the issue, or not, at their own convenience. The most efficient way to get it fixed is that I fix it myself and contribute it back as a good quality patch to the project.

**Comment by jonahgraham** [comment] 2024-03-25 17:18
@piradix Thanks for reporting. This does seem to be related to the new feature described in the [N&N](https://eclipse.dev/eclipse/news/4.31/platform.php#windows-defender-auto-config). Thanks for taking the time to report it.

cc @HannesWell

**Comment by HannesWell** [comment] 2024-03-25 17:40
This could be a duplicate of https://github.com/eclipse-platform/eclipse.platform.ui/issues/1758#issuecomment-2016406009

Can you please try the latest integration build to check if this is already fixed?

**Comment by HannesWell** [comment] 2024-04-06 09:32
Since we got a verification in https://github.com/eclipse-platform/eclipse.platform.ui/issues/1758 that this issue is fixed in the latest integration builds, therefore I'm closing this.
Please re-open if the error persists in that or a later version.

**Closed by HannesWell** 2024-04-06 09:32 UTC
Labels: bug

**Comment by Harshini2407** [comment] 2024-06-04 05:20
Hi ,

I am getting the same error"Windows defender status not retrived"In Detials section I am getting :"Fail retrive comments from windows defender"Unable to Process".Kindly help me to fix this

**Comment by piradix** [comment] 2024-06-04 10:08
I suppose we muist waitting the next vertsion of Eclipse of 2024 jun the (20)  : 
  Version: 2024-06.

**Comment by mikencode** [comment] 2024-06-04 13:58
I'm getting that as well. Let's see what we get in the next update. If anyone finds the fix I'll gladly take it, it's not much but it's just enough annoying to wonder why!

**Comment by piradix** [comment] 2024-06-04 14:57
I've been getting this error dialog box when I open Eclipse for 2 months now. I thought there would be an intermediate update, but no! there are only 16 days left?

I've also lost the about page logo, as well as the one displayed by Windows!

To give you the courage to wait another 15 days, here's a link to what's coming: https://eclipse.dev/eclipse/news/4.32/

**Comment by iostsicaro** [comment] 2024-06-12 03:50
I'm getting that as well. Still appearing for me :((

**Comment by Giovix92** [comment] 2024-06-13 15:53
Used to get it with 4.31.0 (2024-03). 
After upgrading to 4.32.0 (2024-06) and upgrading the workspace I don't get it anymore.

**Comment by AntumDeluge** [comment] 2025-03-06 02:49
@zorglube Same here:

![Image](https://github.com/user-attachments/assets/b97fb1db-7447-4339-bee0-dd8a52286ac5)
