### ISSUE TITLE
Autocomplete hangs, leaves popup in focus, and crashes eclipse

### ISSUE THREAD

**Issue by DerekSansom** [eclipse-platform/.github#96] opened 2023-02-23 15:31 UTC
Regularly using CTRL SPACE to bring up autocomplete options the popup pops up, then stays "computing options"
and when moving from eclipse to another window it stays in focus blocking half the screen
It either stays like this for a couple of minutes then disappears and works as normal for a while, it it stays until eclipsed is forced to close.
In previous versions it didn't do this

Version: 2022-03 (4.23.0)
Build id: 20220310-1457

On Ubuntu 22.04

**Comment by mickaelistria** [comment] 2023-02-23 15:34
Please try latest release, 2022-12 (4.26.0) and report whether the issue is fixed or not.

**Comment by DerekSansom** [comment] 2023-02-27 09:53
I've just updated and now no tests run, and all the class paths are messed
up

**Comment by DerekSansom** [comment] 2023-02-27 09:56
ANd so I shut down eclipse, to restart and see if it will load maven
nature, that it claims is missing although it's installed, and eclipse
won't run at all, thanks very much

**Comment by DerekSansom** [comment] 2023-02-27 10:41
Installed updated eclipse and now

The selected wizard could not be started.

Plug-in org.eclipse.m2e.core.ui was unable to load class
org.eclipse.m2e.core.ui.internal.wizards.MavenImportWizard.

An error occurred while automatically activating bundle
org.eclipse.m2e.core.ui (591).

Everything I try, I'm down some dark nightmare alice in wonderland spiral.
How difficult can this be to make things work

**Comment by laeubi** [comment] 2023-02-27 10:44
> How difficult can this be to make things work

You can open a PR to "make things work" ... beside that explicit steps to reproduce the problem (used version, project, operating system, ...) can help other if they want to look into it.

**Comment by jukzi** [comment] 2023-04-18 08:01
@DerekSansom  please stick to a single problem per issue. Problem of autocomplete hangs can either be
* out of memory -> increase heap memory for eclipse
* performance problem -> please add sampling information (for example with visualvm)

**Comment by Bananeweizen** [comment] 2023-04-18 18:46
This is probably the ibm.icu version conflict issue that was active at the end of last year or so. I've seen similar problems where the m2e.ui bundle could not be activated anymore in previously existing and then upgraded installations. Unfortunately only installing a new eclipse version solved this in all my cases (since you would have to remove the problematic bundle from the old installation, which would then lead to other depending bundles not resolving).

**Closed** 2024-11-20 11:29 UTC
